# Generated by Django 5.2.5 on 2025-08-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_image_productimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='flavor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
