# Generated by Django 5.2.5 on 2025-08-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_productvariation_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
